'use strict'

export { default as LegioCustodes } from './legio-custodes'
export { default as ImperialMilitia } from './imperial-militia'
export { default as LegioTitanicus } from './legio-titanicus'
export { default as MechanicumTaghmata } from './mechanicum-taghmata'
export { default as KnightHousehold } from './knight-household'
export { default as SolarAuxilia } from './solar-auxilia'
export { default as DaemonicHordes } from './daemonic-hordes'
export {default as SpaceMarineLegion } from './space-marine-legion'